"""
Canonical V3 Feature Engineering Engine.
Single authoritative implementation for transforming raw employee features into the V3 feature space.
Must be used by individual inference, batch inference, feature store materialization, and analytics.
"""

from typing import Dict, Any, List, Union
import pandas as pd
import numpy as np
from backend.app.core.logging import logger

# Canonical V3 feature list generated by feature engineering
ENGINEERED_FEATURE_NAMES = [
    "IncomePerJobLevel",
    "PromotionStagnationRatio",
    "ManagerTenureRatio",
    "RoleTenureRatio",
    "OverTimeBinary",
    "CommuteOvertimeBurden",
    "EarlyCareerFlag"
]


def apply_v3_feature_engineering(df: pd.DataFrame, retain_raw_overtime: bool = False) -> pd.DataFrame:
    """
    Transforms a DataFrame of raw employee records into the canonical V3 feature contract.
    
    Expected Raw Input Columns (among standard IBM HR dataset fields):
      - MonthlyIncome
      - JobLevel
      - YearsInCurrentRole
      - YearsSinceLastPromotion
      - YearsWithCurrManager
      - TotalWorkingYears
      - DistanceFromHome
      - OverTime ('Yes' / 'No')
    """
    data = df.copy()
    
    # 1. IncomePerJobLevel
    if "MonthlyIncome" in data.columns and "JobLevel" in data.columns:
        data["IncomePerJobLevel"] = data["MonthlyIncome"] / data["JobLevel"].replace(0, 1)
    elif "IncomePerJobLevel" not in data.columns:
        data["IncomePerJobLevel"] = 0.0

    # 2. PromotionStagnationRatio
    if "YearsInCurrentRole" in data.columns and "YearsSinceLastPromotion" in data.columns:
        data["PromotionStagnationRatio"] = data["YearsInCurrentRole"] / (data["YearsSinceLastPromotion"] + 1)
    elif "PromotionStagnationRatio" not in data.columns:
        data["PromotionStagnationRatio"] = 0.0

    # 3. ManagerTenureRatio
    if "YearsWithCurrManager" in data.columns and "TotalWorkingYears" in data.columns:
        data["ManagerTenureRatio"] = data["YearsWithCurrManager"] / (data["TotalWorkingYears"] + 1)
    elif "ManagerTenureRatio" not in data.columns:
        data["ManagerTenureRatio"] = 0.0

    # 4. RoleTenureRatio
    if "YearsInCurrentRole" in data.columns and "TotalWorkingYears" in data.columns:
        data["RoleTenureRatio"] = data["YearsInCurrentRole"] / (data["TotalWorkingYears"] + 1)
    elif "RoleTenureRatio" not in data.columns:
        data["RoleTenureRatio"] = 0.0

    # 5. OverTimeBinary
    if "OverTime" in data.columns:
        data["OverTimeBinary"] = data["OverTime"].apply(lambda x: 1 if str(x).strip().lower() in ["yes", "1", "true"] else 0)
    elif "OverTimeBinary" not in data.columns:
        data["OverTimeBinary"] = 0

    # 6. CommuteOvertimeBurden
    if "DistanceFromHome" in data.columns and "OverTimeBinary" in data.columns:
        data["CommuteOvertimeBurden"] = data["DistanceFromHome"] * data["OverTimeBinary"]
    elif "CommuteOvertimeBurden" not in data.columns:
        data["CommuteOvertimeBurden"] = 0.0

    # 7. EarlyCareerFlag
    if "TotalWorkingYears" in data.columns:
        data["EarlyCareerFlag"] = (data["TotalWorkingYears"] <= 3).astype(int)
    elif "EarlyCareerFlag" not in data.columns:
        data["EarlyCareerFlag"] = 0

    # Drop raw 'OverTime' if not retained, to match model_metadata_v3.json (raw_overtime_retained: false)
    if not retain_raw_overtime and "OverTime" in data.columns:
        data = data.drop(columns=["OverTime"])

    return data


def transform_single_record(record: Dict[str, Any], retain_raw_overtime: bool = False) -> Dict[str, Any]:
    """Transforms a single raw employee record dictionary using canonical V3 logic."""
    df = pd.DataFrame([record])
    transformed_df = apply_v3_feature_engineering(df, retain_raw_overtime=retain_raw_overtime)
    return transformed_df.iloc[0].to_dict()
