import { Link, useParams } from 'react-router-dom'
import { useBatchPredictions } from '../hooks/useBatchPredictions'

function BatchResults() {
  const { batchId } = useParams()

  const {
    data: predictions = [],
    isPending,
    isError,
    error,
    isFetching,
  } = useBatchPredictions(batchId)

  const highRiskCount = predictions.filter(
    (prediction) =>
      prediction.attrition_prediction === 1,
  ).length

  const averageProbability =
    predictions.length > 0
      ? predictions.reduce(
          (total, prediction) =>
            total +
            Number(
              prediction.attrition_probability || 0,
            ),
          0,
        ) / predictions.length
      : 0

  return (
    <section className="mx-auto max-w-7xl">
      <div>
        <Link
          to="/batches"
          className="text-sm font-medium text-brand-600 hover:underline"
        >
          ← Back to Batches
        </Link>

        <p className="mt-6 text-sm font-medium text-brand-600">
          Batch Results
        </p>

        <h1 className="mt-1 text-2xl font-bold text-slate-900 md:text-3xl">
          Batch Prediction Results
        </h1>

        <p className="mt-2 text-sm text-slate-600">
          Individual employee predictions generated by this
          batch inference job.
        </p>

        <div className="mt-2">
          <span className="rounded-md bg-slate-100 px-2 py-1 font-mono text-xs text-slate-600">
            {batchId}
          </span>
        </div>
      </div>

      {isPending && (
        <div className="mt-8 rounded-xl border border-slate-200 bg-white p-6">
          <p className="text-sm text-slate-500">
            Loading batch predictions...
          </p>
        </div>
      )}

      {isError && (
        <div className="mt-8 rounded-xl border border-red-200 bg-red-50 p-6">
          <p className="font-medium text-red-700">
            Unable to load batch predictions.
          </p>

          <p className="mt-1 text-sm text-red-600">
            {error?.message}
          </p>
        </div>
      )}

      {!isPending && !isError && (
        <>
          <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <MetricCard
              label="Employees"
              value={predictions.length}
            />

            <MetricCard
              label="High Risk"
              value={highRiskCount}
            />

            <MetricCard
              label="Review Rate"
              value={
                predictions.length > 0
                  ? `${(
                      (highRiskCount /
                        predictions.length) *
                      100
                    ).toFixed(1)}%`
                  : '0%'
              }
            />

            <MetricCard
              label="Average Risk"
              value={`${(
                averageProbability * 100
              ).toFixed(2)}%`}
            />
          </div>

          <section className="mt-8 overflow-hidden rounded-xl border border-slate-200 bg-white">
            <div className="flex items-center justify-between border-b border-slate-200 p-6">
              <div>
                <h2 className="font-semibold text-slate-900">
                  Employee Predictions
                </h2>

                <p className="mt-1 text-sm text-slate-500">
                  Model output for each employee in the
                  uploaded CSV.
                </p>
              </div>

              {isFetching && (
                <span className="text-xs text-slate-500">
                  Refreshing...
                </span>
              )}
            </div>

            {predictions.length === 0 ? (
              <p className="p-6 text-sm text-slate-500">
                No prediction records were found for this
                batch.
              </p>
            ) : (
              <div className="overflow-x-auto">
                <table className="min-w-full text-left text-sm">
                  <thead className="border-b border-slate-200 bg-slate-50">
                    <tr>
                      <th className="px-6 py-3 font-medium text-slate-600">
                        Prediction
                      </th>

                      <th className="px-6 py-3 font-medium text-slate-600">
                        Probability
                      </th>

                      <th className="px-6 py-3 font-medium text-slate-600">
                        Decision
                      </th>

                      <th className="px-6 py-3 font-medium text-slate-600">
                        Recommendation
                      </th>

                      <th className="px-6 py-3 font-medium text-slate-600">
                        Threshold
                      </th>

                      <th className="px-6 py-3 font-medium text-slate-600">
                        Latency
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    {predictions.map((prediction) => {
                      const probability =
                        Number(
                          prediction.attrition_probability ||
                            0,
                        ) * 100

                      const isHighRisk =
                        prediction.attrition_prediction ===
                        1

                      return (
                        <tr
                          key={prediction.prediction_id}
                          className="border-b border-slate-100 last:border-0"
                        >
                          <td className="px-6 py-4">
                            <p className="font-medium text-slate-900">
                              {prediction.prediction_id}
                            </p>
                          </td>

                          <td className="px-6 py-4">
                            <span className="font-semibold text-slate-900">
                              {probability.toFixed(2)}%
                            </span>
                          </td>

                          <td className="px-6 py-4">
                            <span
                              className={`rounded-full px-2.5 py-1 text-xs font-semibold ${
                                isHighRisk
                                  ? 'bg-red-100 text-red-700'
                                  : 'bg-emerald-100 text-emerald-700'
                              }`}
                            >
                              {isHighRisk
                                ? 'Attrition Risk'
                                : 'Low Risk'}
                            </span>
                          </td>

                          <td className="px-6 py-4 text-slate-600">
                            {prediction.risk_recommendation}
                          </td>

                          <td className="px-6 py-4 text-slate-600">
                            {(
                              Number(
                                prediction.selected_threshold ||
                                  0,
                              ) * 100
                            ).toFixed(0)}
                            %
                          </td>

                          <td className="px-6 py-4 text-slate-600">
                            {Number(
                              prediction.latency_ms || 0,
                            ).toFixed(2)}{' '}
                            ms
                          </td>
                        </tr>
                      )
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </section>
        </>
      )}
    </section>
  )
}

function MetricCard({ label, value }) {
  return (
    <article className="rounded-xl border border-slate-200 bg-white p-5">
      <p className="text-sm text-slate-500">
        {label}
      </p>

      <p className="mt-2 text-2xl font-bold text-slate-900">
        {value}
      </p>
    </article>
  )
}

export default BatchResults